version: '3'
services:
  goods-products-api:
    image: book-personalize-api:latest
    container_name: book-personalize-api
    command: npm run dev
    volumes:
      - ./src:/home/node/api/src
      - ./package.json:/home/node/api/package.json
      - ./.env:/home/node/api/.env
      - ./.env.example:/home/node/api/.env.example
      - ./.babelrc:/home/node/api/.babelrc
      - ./.eslintrc:/home/node/api/.eslintrc
    ports:
      - '9000:9000'
    environment:
      NODE_ENV: development
      PORT: 9000
      TZ: Asia/Seoul
    tty: true
    links:
      - book-personalize-mysql

  book-personalize-mysql:
    image: mysql:8
    container_name: book-personalize-mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql-mode=''
    restart: always
    ports:
      - '9100:3306'
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: api_dev
      TZ: Asia/Seoul
